# Generated by Django 5.2.5 on 2025-09-23 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_alter_pokemon_evolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 15, 48, 42, 660281)),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 15, 48, 42, 660306)),
        ),
    ]
