# Generated by Django 5.2.5 on 2025-09-23 16:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_alter_pokemonentity_appeared_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(default='Описание отсутствует', max_length=1000, verbose_name='Описание покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='pokemon_entities.pokemon', verbose_name='Эволюции покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='Изображение покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(default='Покемон', max_length=50, verbose_name='Название покемона на русском языке'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(default='Pokemon', max_length=50, verbose_name='Название покемона на английском языке'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(default='ポケモン', max_length=50, verbose_name='Название покемона на японском языке'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 16, 8, 43, 543931), verbose_name='Время появление сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='damage',
            field=models.IntegerField(default=0, verbose_name='Очки урона сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='defense',
            field=models.IntegerField(default=0, verbose_name='Очки защиты сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 16, 8, 43, 543942), verbose_name='Время исчезновения сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(default=0, verbose_name='Очки здоровья сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Географическая широта сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(default=0.0, verbose_name='Географическая долгота сущности покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон, связаный с данной сущностью покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='stamina',
            field=models.IntegerField(default=0, verbose_name='Очки выносливости сущности покемона'),
        ),
    ]
